### ISSUE TITLE
userStore.setUser() should occur after login and signup

### ISSUE THREAD

**Issue by TheNaschkatze** [DialBird/vite-firebase#1]
Hi, first of all... great work.

I was thinking why don't you load the user store after registering/login immediately. I mean inside the actions in the authStore.

cheers!

**Comment by DialBird** [comment]
Hi Alonso.
Thanks for your comment! lol

I was not thinking so deeply.
I just delegate that task to "LayoutDashboard component", because I make sure to router.push to pages under "LayoutDashboard" after login or signup.
